name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    environment: productive-box
    steps:
      - name: Update gist
        uses: Asmedeus998/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 84e2293e8215c1cf5f1b8cb468314248
          TIMEZONE: Asia/Taipei
